import Head from "next/head";

import { Inter } from "next/font/google";
import BodyLayout from "@/layout/Body/BodyLayout";
import {HeaderLayout} from "@/layout/Header/HeaderLayout";
import {MainLayout} from "@/layout/Main/MainLayout";
import {Footer} from "@/layout/Footer/Footer";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
     <BodyLayout>
         <HeaderLayout/>
         <MainLayout/>
         <Footer/>
     </BodyLayout>
    </>
  );
}
